Parameters:
  AddResponses:
    Blanks:
    - D1
    CVthreshold: 0.2
    DesignFile: ../Step1/AccuracytestPostMixConcOutput_Arnold.xlsx
    DesignFiletype: JMP
    Diluent: water
    Extinctioncoefficient: 20330
    FindOptWavelength: true
    ManualComparison: false
    MarsResultsFileXLSX: platereaderresults.xlsx
    Molecule: tartrazine
    OutputFilename: null
    PlateType: greiner384
    R2threshold: 0.7
    ReadingTypeinMarsFile: Abs Spectrum
    Responsecolumntofill: Absorbance
    Sheet: 0
    StockEqualsTotalVolPerWell: true
    StockconcinMperL: 0.0002878191305957933M/l
    Stockvol: 100ul
    VolumeToManualwells:
      0.347 ul:
      - A1
      - B1
      - C1
    Wavelength: 472
    WellForScanAnalysis: J2
