Parameters:
  AccuracyTest:
    DXORJMP: JMP
    Diluent: water
    DilutionFactor: 10
    Imagefilename: star.png
    LHPolicy: PostMix
    MinVolume: 1ul
    NumberofBlanks: 0
    NumberofReplicates: 4
    OutPlate: greiner384_riser40
    OutputFilename: 180117AccuracytestPostMixConcOutput_Arnold.xlsx
    Printasimage: false
    StockConcentrations:
    - 0.2878191305957933mM
    TestSolConcs:
    - 0.0uM
    - 0.5uM
    - 1uM
    - 2uM
    - 4uM
    - 8uM
    TestSols:
    - tartrazine
    TotalVolume: 100ul
    UseLiquidPolicyForTestSolutions: true
    WellsUsed: 39
