{
    "Parameters": {
        "AccuracyTest": {
            "Diluent": "water",
            "TestSols": [
			"tartrazine"
			],
            "NumberofReplicates": 5,
            "OutPlate": "greiner384_riser",
            "TestSolVolumes": [
			"25ul",
			"30ul",
			"35ul",
			"40ul",
			"45ul",
			"50ul"
			],
			"UseLiquidPolicyForTestSolutions": true,
			"LHPolicy":"PostMix",
			"DXORJMP":"JMP",
			"OutputFilename":"AccuracytestPostMixHVoutput_test.xlsx",
			"Printasimage": true,
			"Imagefilename": "star.png",
            "TotalVolume": "100ul",
			"NumberofBlanks": 1
        }
    }
}

