{
    "Parameters": {
		"addplate": {
             "InputCSVfile":"inputplate.csv"
	 },
	"transfer": {
             "Liquidname":"testliquid",
			"LiquidVolume":"10ul",
			"Startingsolution":"10g/Lglycerol"
	 }
    }
}
