{
    "Parameters": {
        "Transformation": {
            "CompetentCellvolumeperassembly": "50ul",
            "OutPlate": "pcrplate_with_cooler",
            "Postplasmidtemp": "2C",
            "Postplasmidtime": "300s",
            "Reaction": "dna_part",
            "Reactionvolume": "10ul",
            "ReadyCompCells": "neb5compcells"
        }
    }
}
