{
    "Parameters": {
        "DiluteBuffer": {
            "Bufferstock": "Acid yellow 23",
            "Bufferstockconc": "0.006M/l",
            "BufferVolumeAdded": "1ul",
            "Diluent": "water",
            "DiluentVolume": "45ul",
            "OutPlate": "pcrplate_with_cooler"
        }
    }
}
