{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"cmyk2.jpg",
		"Rotate": false,
		"AutoRotate": true,
      "Cyan": "Cyan",
	"Magenta": "Magenta",
	"Yellow": "Yellow_ink",
	"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "150ul"
    }
  }
}


