{
    "Parameters": {
        "Assaysetup": {
            "Buffer": "water",
            "Enzyme": "T4Ligase",
            "EnzymeVolume": "1ul",
            "NumberofReactions": 1,
            "OutPlate": "pcrplate_skirted",
            "Substrate": "CutsmartBuffer",
            "SubstrateVolume": "2ul",
            "TotalVolume": "10ul"
        }
    }
}
