{
    "Parameters": {
        "Standarddigest_conc": {
           "BSAoptional": "DNAsolution",
           "BSAvol": "0ul",
           "Buffer": "CutsmartBuffer",
           "BufferConcX": 10,
           "DNAConc": "50ng/ul",
           "DNAMassperReaction": "100ng",
           "DNAName": "BBa_J23104",
           "DNASolution": "DNAsolution",
           "DesiredConcinUperml": [
               10,
			10
           ],
           "EnzSolutions": [
               "restrictionenzyme",
			"restrictionenzyme"
           ],
           "EnzymeNames": [
               "EcoRI",
			"SpeI"
           ],
           "InactivationTemp": "80C",
           "InactivationTime": "1200s",
           "OutPlate": "pcrplate_with_cooler",
			"Platenumber": 1,
           "ReactionTemp": "37C",
           "ReactionTime": "600s",
           "ReactionVolume": "25ul",
           "StockReConcinUperml": [
               10000,
			10000
           ],
           "Water": "water"
        }
    }
}
