{
    "Parameters": {
        "newparams": {
            "LiquidVolume": "100ul",
            "Liquidname": "Evian",
            "OutPlate": "pcrplate_skirted_riser40",
            "Startingsolution": "water"
        }
    }
}
