Parameters:
  SerialDilute:
    ByRow: false
    Diluent: water
    DilutionFactor: 10
    NumberOfDilutions: 16
    OutPlate: DSW96_riser
    RemoveExcessSolution: true
    Solution: tartrazine
    TotalVolumeperDilution: 100ul
    WellsAlreadyUsed: 0
