{
    "Parameters": {
        "Mastermix_reaction": {
            "AliquotbyRow": false,
            "ComponentVolumesperReaction": [
                "2ul",
                "1ul",
                "1ul",
                "1ul"
            ],
            "Components": [
                "CutsmartBuffer",
                "T4Ligase",
                "SapI",
                "ATP"
            ],
            "Inplate": "Kombi2mlEpp",
            "NumberofMastermixes": 1,
            "OutPlate": "pcrplate_with_cooler",
            "Reactionspermastermix": 10,
            "TopUpBuffer": "water",
            "TotalVolumeperreaction": "20ul",
            "VolumetoLeaveforDNAperreaction": "5ul"
        }
    }
}
