{
    "Parameters": {
        "newparams": {
            "LiquidVolumes": ["19ul","100ul"],
            "Liquidname": "tartrazine",
            "OutPlates": [
			"pcrplate_skirted",
            "pcrplate_skirted_riser20",
			"pcrplate_skirted_riser40",
			"pcrplate_skirted_incubator",
            ],
            "LiquidTypes": ["water","NeedToMix", "DispenseAboveLiquid"],
            "Startingsolution": "tartrazine",
           
			"TestName":"pcrplate+postrefactor"
        }
    }
}
