Parameters:
  newparams:
    LiquidTypes:
    - water
    - NeedToMix
    - DispenseAboveLiquid
    LiquidVolumes:
    - 19ul
    - 100ul
    Liquidname: tartrazine
    OutPlates:
    - pcrplate_skirted
    - pcrplate_skirted_riser20
    - pcrplate_skirted_riser40
    - pcrplate_skirted_incubator
    Startingsolution: tartrazine
    TestName: pcrplate+postrefactor
