Parameters:
  PCR:
    AddPrimerstoMasterMix: true
    AdditiveVols: []
    Additives: []
    AnnealingTemp: 60C
    Annealingtime: 10s
    Buffer: HC
    BufferConcinX: 10
    DNTPS: DNTPs
    DNTPVol: 1ul
    Denaturationtime: 5s
    Extensiontime: 60s
    Finalextensiontime: 600s
    FwdPrimer: PrimerFw
    FwdPrimerVol: 1ul
    Hotstart: true
    InitDenaturationtime: 30s
    Numberofcycles: 25
    OutPlate: pcrplate_with_cooler
    PCRPolymerase: Q5Polymerase
    PolymeraseVolume: 1ul
    ReactionVolume: 20ul
    RevPrimer: PrimerRev
    RevPrimerVol: 1ul
    Template: pET_GFP
    Templatevolume: 2ul
    Water: water
