{
    "Parameters": {
        "PCR": {
            "AdditiveVols": [
			],
            "Additives": [],
			"BufferConcinX":10,
			"PolymeraseVolume":"1ul",
            "AnnealingTemp": "60C",
            "Annealingtime": "10s",
            "Buffer": "HC",
            "DNTPS": "DNTPs",
            "DNTPVol": "1ul",
            "Denaturationtime": "5s",
            "Extensiontime": "60s",
            "Finalextensiontime": "600s",
            "FwdPrimer": "PrimerFw",
            "FwdPrimerVol": "1ul",
            "InitDenaturationtime": "30s",
            "Numberofcycles": 25,
            "OutPlate": "pcrplate_with_cooler",
            "PCRPolymerase": "Q5Polymerase",
            "ReactionVolume": "20ul",
            "RevPrimer": "PrimerRev",
            "RevPrimerVol": "1ul",
            "Template": "pET_GFP",
            "Templatevolume": "2ul",
			"Hotstart":true,
			"AddPrimerstoMasterMix":true,
			"Water":"water"
        }
    }
}


