Parameters:
  AliquotParams:
    NumberOfReplicaPlates: 1
    NumberofAliquots: 8
    OutPlate: pcrplate_with_cooler
    Solution: water
    SolutionVolume: 4000ul
    VolumePerAliquot: 25ul
    WellsAlreadyUsed: 0
  AliquotParams2:
    NumberOfReplicaPlates: 1
    NumberofAliquots: 8
    OutPlate: pcrplate_with_cooler
    Solution: water
    SolutionVolume: 4000ul
    VolumePerAliquot: 25ul
    WellsAlreadyUsed: 8
  AliquotParams3:
    NumberOfReplicaPlates: 1
    NumberofAliquots: 8
    OutPlate: pcrplate_with_cooler
    Solution: fluorescein
    SolutionVolume: 4000ul
    VolumePerAliquot: 25ul
    WellsAlreadyUsed: 16
  AliquotParams4:
    NumberOfReplicaPlates: 1
    NumberofAliquots: 8
    OutPlate: pcrplate_with_cooler
    Solution: fluorescein
    SolutionVolume: 4000ul
    VolumePerAliquot: 25ul
    WellsAlreadyUsed: 24
