{
    "Parameters": {
        "Evaporationrate": {
            "Airvelocity": "0m/s",
            "Executiontime": "4h",
            "Liquid": "fluorescein",
            "Pa": "102000Pa",
            "Platetype": "pcrplate_skirted",
            "Relativehumidity": 0.31,
            "Temp": "31.4C",
            "Volumeperwell": "100ul"
        }
    }
}
