Parameters:
  Mastermix:
    ComponentVolumesperReaction:
    - 2ul
    - 1ul
    - 1ul
    - 1ul
    Components:
    - CutsmartBuffer
    - T4Ligase
    - SapI
    - ATP
    NumberofReactions: 50
    OutPlate: pcrplate_skirted_riser
