{
    "Parameters": {
        "Transformation": {
            "Postplasmidtemp": "2C",
            "Postplasmidtime": "300s",
            "Reactions": [
			"dna_part"
			],
            "Reactionvolume": "2ul",
            "ReadyCompCells": [
			"neb5compcells"
			],
			"RecoveryMediaAliquots":[
			"LB"
			],
			"Recoverytemp":"37C",
			"Recoverytime":"7200s"
        }
    }
}
