{
    "Parameters": {
        "PlateOut": {
            "AgarPlate": "pcrplate_with_cooler",
            "Diluent": "water",
            "DilutionX": 10,
            "IncubationTemp": "25C",
            "IncubationTime": "57600s",
            "Plateoutvolume": "10ul",
            "RecoveredCells": "neb5compcells"
        }
    }
}
