Parameters:
  PlateOut:
    AgarPlate: falcon6wellAgar
    AgarPlateNumber: 1
    IncubationTemp: 37C
    IncubationTime: 57600s
    NumberofReplicates: 2
    PlateOutLiquidPolicy: plateout
    PlateOutVolume: 100ul
    TransformedCells: neb5compcells
    WellsAlreadyUsed: 0
