{
    "Parameters": {
        "PrimerDesign": {
            "Dirname": "sequences",
            "Maxtemp": "60C",
            "Mintemp": "55C",
            "Maxgc": 0.6,
            "Minlength": 20,
			"Maxlength":25,
			"PermittednucleotideOverlapBetweenPrimers":20,
			"ExportToFile":true
        }
    }
}
