{
    "Parameters": {
        "Standarddigestparams": {
            "BSAoptional": "DNAsolution",
            "BSAvol": "0ul",
            "Buffer": "CutsmartBuffer",
            "BufferVol": "2ul",
            "DNAName": "vector1",
            "DNASolution": "DNAsolution",
            "DNAVol": "1ul",
            "EnzSolutions": [
                "restrictionenzyme"
            ],
            "EnzVolumestoadd": [
                "1ul"
            ],
            "EnzymeNames": [
                "Nco1"
            ],
            "InPlate": "pcrplate_with_cooler",
            "InactivationTemp": "65C",
            "InactivationTime": "10s",
            "OutPlate": "pcrplate_with_cooler",
            "ReactionTemp": "37C",
            "ReactionTime": "3600s",
            "ReactionVolume": "20ul",
            "Water": "water"
        }
    }
}
