{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"veryblack",
	  	"Imagefilename": "rainbow1.png",
		"Rotate": false,
		"AutoRotate": true,
		"Palettename":"ProteinPaintboxSubset",
		"Subset": false,
		"Subsetnames": [
				"DreidelTeal",
				"TinselPurple",
				"CupidPink",
				"LeorOrange",
				"KringleYFP",
				"DasherGFP",
				"RudolphRFP",
				"FresnoRFP",
				"IvyGFP",
				"TwinkleCFP",
				"BlitzenBlue",
				"YetiYFP",
				"YukonOFP",
				"HollyGFP",
				"CometGFP",
				"veryblack",
				"JuniperGFP"
				],
		"UseLiquidClass":"water",
      	"OutPlate": "Agarplateforpicking768_riser",
		"UVimage":false,
      	"VolumePerWell": "2ul"
    }
  }
}
