{
    "Parameters": {
        "EnterNameForYourParameters1": {
            "InputVariable": "Some component in factory",
            "OutPlate": "greiner384",
            "ParameterVariableAsValuewithunit": "10ul",
            "ParameterVariableAsint": 1,
            "ParameterVariablestring": "Hello World!"
        },
        "EnterNameForYourParameters2": {
            "InputVariable": "Some component in factory",
            "OutPlate": "greiner384",
            "ParameterVariableAsValuewithunit": "100ul",
            "ParameterVariableAsint": 2,
            "ParameterVariablestring": "Hello again"
        }
    }
}
