Parameters:
  fasta:
    Database: nucleotide
    Filename: accD.fasta
    ID: opuntia[ORGN] accD
    MaxReturns: 1
    ReturnType: fasta
  genbank:
    Database: nucleotide
    Filename: accD.gb
    ID: opuntia[ORGN] accD
    MaxReturns: 1
    ReturnType: gb
  xml:
    Database: nucleotide
    Filename: ""
    ID: opuntia[ORGN] accD
    MaxReturns: 1
    ReturnType: xml
