{
    "Parameters": {
        "Assay_quench": {
            "Quenchingagent": "water",
            "Enzyme": "T4Ligase",
            "EnzymeVolume": "3ul",
            "OutPlate": "pcrplate_skirted",
            "Substrate": "dna_part",
            "SubstrateVolume": "3ul",
			"QuenchingagentVolume": "14ul",
            "ReactionTemp": "25C",
            "ReactionTime": "300s"
        }
    }
}
