{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"vader.jpeg",
		"Rotate": false,
		"AutoRotate": true,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.3,
		"MaxBlackPercentagethreshold": 0.7,
		"OnlyHighVolumetips": false,
		"SkipWhite": true,
		"MixingLiquidClass": "NeedToMix",
		"NonMixingClass": "water",
		"DontMix":true,
		"Negative": false,
		"PosterizeImage": true,
		"PosterizeLevels": 2,
		"Black": "Black",
      "OutPlate": "greiner384",
      "VolumeForFullcolour": "25ul"
    }
  }
}



