{
    "Parameters": {
       "Recovery": {
			"TransformedcellVolume":"50ul",
            "Recoverymedium": "LB",
            "Recoverytemp": "25C",
            "Recoverytime": "57600s",
            "Recoveryvolume": "500ul",
            "Transformedcells": "neb5compcells"
        }
    }
}
