{
  "Parameters": {
    "PreProcess": {
		"Imagefilename":"nyancat.jpg",
		"CheckAllResizeAlgorithms": false,
		"Rotate": false,
		"AutoRotate": true,
		"PosterizeImage":false,
		"PosterizeLevels":8,
      "Palette":"Neon",
	  "Negative":false,
	  "OutPlate":"greiner384_riser"
    }
  }
}


