{
    "Parameters": {
        "Transformation_complete": {
            "CompetentCellvolumeperassembly": "50ul",
            "OutPlate": "pcrplate_with_cooler",
            "Preplasmidtime": "300s",
            "Preplasmidtemp": "2C",
            "Postplasmidtemp": "2C",
            "Postplasmidtime": "300s",
            "Reaction": "dna_part",
            "Reactionvolume": "10ul",
			"Recoverymedium": "LB",
            "Recoverytemp": "25C",
            "Recoverytime": "57600s",
            "Recoveryvolume": "500ul",
            "CompetentCells": "neb5compcells",
			"AgarPlate": "falcon6wellAgar",
			"Plateoutvolume": "100ul"
        }
    }
}
