{
    "Parameters": {
        "Transformation1": {
            "CompetentCellvolumeperassembly": "50ul",
            "OutPlate": "pcrplate_with_cooler",
            "Postplasmidtemp": "2C",
            "Postplasmidtime": "300s",
            "Reaction": "dna_part",
            "Reactionvolume": "2ul",
            "ReadyCompCells": "neb5compcells"
			},
		"Recovery1": {  
            "Recoverytemp": "25C",
            "Recoverytime": "57600s",
            "Recoveryvolume": "500ul",
			"TransformedcellVolume":"50ul",
			"Recoverymedium": "LB"
			},
		"PlateOut1": {
           "Plateoutvolume": "100ul",
		   "IncubationTemp":"37C",
		   "IncubationTime": "36000s",
		   "DilutionX": 2,
		   "Diluent": "water",
           "AgarPlate": "falcon6wellAgar"
			}
        }
    
}
