{
    "Parameters": {
        "PROMOTER": {
            "OnlyreturnAvailableParts": false,
            "OnlyreturnWorkingparts": false,
			"ExactTypeOnly":true,
			"MatchAllDescriptions":false,
            "Partdescriptions": [
				"PROMOTER",
				"T5"
            ],
            "Parttype":
                "REGULATORY"
            
        },
		"RBS": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": true,
			"ExactTypeOnly":true,
			"MatchAllDescriptions":true,
            "Partdescriptions": [
				"RBS",
               "STRONG"
            ],
            "Parttype":
                "GENERIC"
            
        },
		"RedReporter": {
            "OnlyreturnAvailableParts": false,
            "OnlyreturnWorkingparts": false,
			"ExactTypeOnly":true,
			"MatchAllDescriptions":false,
            "Partdescriptions": [
               "RED",
			   "Red",
			   "RFP",
			   "mCherry"
            ],
            "Parttype":
                "REPORTER"
            
        },
		"YellowReporter": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": false,
			"ExactTypeOnly":true,
			"MatchAllDescriptions":true,
            "Partdescriptions": [
               "YELLOW"
            ],
            "Parttype":
                "REPORTER"
            
        },
		"GreenReporter": {
            "OnlyreturnAvailableParts": false,
            "OnlyreturnWorkingparts": false,
			"ExactTypeOnly":true,
			"MatchAllDescriptions":false,
            "Partdescriptions": [
               "GREEN",
			   "Green",
			   "green",
			   "GFP",
			   "gfp"
            ],
            "Parttype":
                "REPORTER"
            
        }
    }
}
