{
    "Parameters": {
        "ConstructAssembly_sim": {
            "Atp": "ATP",
            "AtpVol": "1ul",
            "Buffer": "CutsmartBuffer",
            "BufferVol": "2ul",
            "Constructname": "MyfavouriteConstruct",
            "InPlate": "pcrplate_with_cooler",
            "InactivationTemp": "40C",
            "InactivationTime": "60s",
            "LigVol": "1ul",
            "Ligase": "T4Ligase",
            "OutPlate": "pcrplate_with_cooler",
            "PartConcs": [
                "0.1g/l",
                "0.11g/l"
            ],
            "PartVols": [
                "1ul",
                "1ul"
            ],
            "Parts": [
                "dna_part",
                "dna_part"
            ],
            "Partsinorder": [
                "Part1",
                "Part2"
            ],
            "ReVol": "1ul",
            "ReactionTemp": "25C",
            "ReactionTime": "1800s",
            "ReactionVolume": "20ul",
            "RestrictionEnzyme": "SapI",
            "Vector": "standard_cloning_vector_mark_1",
            "VectorConcentration": "0.01M/l",
            "VectorVol": "3ul",
            "Vectordata": "Vector1",
            "Water": "water"
        }
    }
}
