{
    "Parameters": {
        "DNAgelParams1": {
              "DNAgel": "EGEL96_1",
              "DNAgelrunvolume": "15ul",
  			"LadderVolume":"10ul",
              "Ladder": "1kb DNA Ladder",
              "Loadingdye": "blue",
              "Loadingdyeinsample": true,
              "Loadingdyevolume": "1ul",
              "MixPlate": "pcrplate_skirted_riser",
              "Mixingpolicy": "load",
              "ProjectName": "Test",
              "Samplenames": [
                  "1",
                  "2",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9"
              ],
              "Samplenumber": 1,
              "Sampletotest": "dna_part",
              "Water": "water",
              "Watervol": "10ul"
        }
    }
}
