Parameters:
  DNAgelParams1:
    GelLoadingMixingPolicy: load
    LadderVolume: 10ul
    LoadingDyeInSample: false
    LoadingDyeMixingPolicy: NeedToMix
    LoadingDyeVolume: 5ul
    OptimisePlateUsage: false
    Replicates: 1
    TotalVolumePerWell: 15ul
    WaterVolume: 5ul
    DNAGel: EGEL96_1
    Ladder: 1kb DNA Ladder
    LoadingDye: blue
    MixPlate: greiner384_riser20
    Reactions:
    - dna
    - dna
    - dna
    Water: water
