Parameters:
  DNAgelParams1:
    DNAGel: EGEL48
    GelLoadingMixingPolicy: load
    Ladder: 1kb DNA Ladder
    LadderVolume: 10ul
    LoadingDye: blue
    LoadingDyeInSample: false
    LoadingDyeMixingPolicy: NeedToMix
    LoadingDyeVolume: 5ul
    MixPlate: greiner384_riser20
    OptimisePlateUsage: false
    Reactions:
    - dna
    - dna
    - dna
    Replicates: 1
    SampleVolume: 5ul
    Water: water
