Parameters:
  MultiChannelTest:
    OutputPlateType: pcrplate_skirted_riser
    Parts:
    - water
    - ATP
    - T4Ligase
    - dna_part
    - SapI
    - standard_cloning_vector_mark_1
    - CutsmartBuffer
    - tartrazine
    Vols:
    - 1ul
    - 1ul
    - 1ul
    - 1ul
    - 1ul
    - 1ul
    - 1ul
    - 1ul
