{
      "Parameters": {
	"Design1": {
	            "Parts": [
					"U28422.1",
					"EF208560"	
				],
				"Vector": "HQ398611.1",
				"RE": "SapI",
				"EndsAlreadyAdded":false,
				"SynthesisProvider":"GenScript",
				"ConstructName":"Construct_test",
				"ExporttoFastaFile":false
			}
		}
}
