Parameters:
  Design1:
    ConstructName: Construct_test
    EndsAlreadyAdded: false
    ExporttoFastaFile: false
    Parts:
    - U28422.1
    - EF208560
    RE: SapI
    SynthesisProvider: GenScript
    Vector: HQ398611.1
