{
    "Parameters": {
        "LoadGel1": {
            "GelPlate": "EPAGE48",
            "InPlate": "pcrplate_with_cooler",
            "LoadVolume": "10ul",
            "Protein": "Load",
            "SampleNames": [
			"Marker",
			"NegativeControl",
			"GFP",
			"RFP",
			"YFP",
			"CFP",
			"OFP"
			],
            "Water": "water",
            "WaterName": "dH2O",
            "WaterVolume": "10ul"
        }
}
}