{
    "Parameters": {
        "Kla": {
            "D": 2.1e-09,
            "Fillvolume": "1000ul",
            "Liquid": "water",
            "Platetype": "24DSW_pyramid",
            "Rpm": "200/min",
            "Shakertype": "Kuhner",
            "TargetRE": 226659.867
        }
    }
}
