{
    "Parameters": {
        "RemoveRestrictionSites": {
            "EnzymeforRestrictionmapping": "BsaI",
            "PreserveTranslatedseq": true,
            "RemoveifnotinORF": true,
            "RestrictionsitetoAvoid": [
                "SacI"
            ],
            "Sequencekey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGAGCTCGGGGGGGGGGGGGGGGGGGGGGGGG"
        }
    }
}
