{
    "Parameters": {
        "Mastermix": {
            "Reactionspermastermix": 25,
            "ComponentVolumesperReaction": [
                "2ul",
                "1ul",
                "1ul",
                "1ul"
            ],
            "Components": [
                "CutsmartBuffer",
                "T4Ligase",
                "SapI",
                "ATP"
            ],
            "OutPlate": "pcrplate_with_cooler"
           
        }
    }
}
